version: '3'

tasks:
  generate-wizexercise.txt:
    desc: Generate wizexercise.txt with the encoded answer
    cmds:
      - |
        echo "The answer to the ultimate question of life, the universe and everything: 42" | base64 > wizexercise.txt